version: '2.1'

orbs:
  android: circleci/android@2.0

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

references:

  android-executor: &android-executor
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1

jobs:

  build-qa:
    <<: *android-executor
    steps:
      - run: git pull --all
      - checkout
      - run:
          name: Assemble QA
          command: ./gradlew assembleQaRelease

  build-prod:
    <<: *android-executor
    steps:
      - checkout
      - run:
          name: Assemble PROD
          command: ./gradlew assembleProdRelease

workflows:

  build:
    when:
      equal: [ "build", << pipeline.parameters.GHA_Action >> ]
    jobs:
      - build-qa

  feature-build:
    when:
      equal: [ "feature-build", << pipeline.parameters.GHA_Action >> ]
    jobs:
      - build-qa
